import { PurchaseRequisitionRespType } from 'api/prApi.types.js'

import createBCSHeaderSection from 'components/pdf/BCSHeaderSection.js'
import createBCSTableSection from 'components/pdf/BCSTableSection.js'

import { formatDisplayDate } from 'utils/dateHelpers.js'

import pdfMake from 'pdfmake/build/pdfmake'
import { TDocumentDefinitions } from 'pdfmake/interfaces'

// @ts-expect-error vfs_fonts.js a custom file generated by pdfmake
import { vfs } from '../../../../pdfmake/vfs_fonts.js'

import createHeaderSection from './HeaderSection.js'
import createItemsTableSection from './ItemsTableSection.js'
import createPRInfoSection from './PRInfoSection.js'
import createSignatureSection from './SignatureSection.js'

// Initialize pdfMake
pdfMake.vfs = vfs

pdfMake.fonts = {
  Sarabun: {
    normal: 'Sarabun-Regular.ttf',
    bold: 'Sarabun-Bold.ttf',
    italics: 'Sarabun-Italic.ttf',
    bolditalics: 'Sarabun-BoldItalic.ttf',
  },
}

/**
 * Creates a PDF document definition for a Purchase Requisition
 * @param prData The Purchase Requisition data
 * @returns A pdfMake document definition
 */
export const createPRDocumentDefinition = (prData: PurchaseRequisitionRespType): TDocumentDefinitions => {
  return {
    footer: function (currentPage: number, pageCount: number) {
      return {
        text: 'Page ' + currentPage.toString() + '/' + pageCount,
        alignment: 'right',
        margin: [0, 0, 10, 0],
      }
    },
    header: undefined,
    content: [
      // NOTE: ------ PR PAGE ------
      {
        margin: [-20, -30, -20, 0],
        layout: {
          // paddingBottom: TABLE_LAYOUT.paddingBottom,
          defaultBorder: false,
        },
        table: {
          headerRows: 4,
          keepWithHeaderRows: 1,
          dontBreakRows: true,
          widths: [20, '*', 35, 40, 65, 60, 65],
          body: [
            // NOTE: ------ HEADER ------
            createHeaderSection(prData),
            ...createPRInfoSection(prData),
            // NOTE: ------ ITEMS TABLE SECTION ------
            ...createItemsTableSection(prData),
            // NOTE: ---- Signature Section ----
            createSignatureSection(prData),
          ],
        },
      },
      // NOTE: ------ BUDGET CONTROL SHEET PAGE ------
      {
        margin: [-20, -30, -20, 0],
        pageBreak: 'before',
        layout: {
          // paddingTop: TABLE_LAYOUT.paddingTop,
          defaultBorder: false,
        },
        table: {
          widths: ['*'],
          body: [
            // NOTE: ------ HEADER ------
            createBCSHeaderSection({
              documentNo: prData.prNo,
              documentDate: formatDisplayDate(prData.prDate),
            }),
          ],
        },
      },
      {
        margin: [-20, 0, -20, 0],
        layout: {
          defaultBorder: true,
        },
        table: {
          widths: [
            20, // Fixed first column
            40, // Fixed second column
            70, // Fixed third column
            ...prData.purchaseRequisitionBudgetControlSheets.map(() => '*'), // Dynamic budget columns
          ],
          body: [
            ...createBCSTableSection({
              domain: 'PURCHASE_REQUISITION',
              budgets: prData.purchaseRequisitionBudgetControlSheets,
              budgetTypeName: prData.budgetTypeName,
              bcsRemark: prData.budgetControlSheetRemark,
            }),
          ],
        },
      },
    ],
    defaultStyle: {
      font: 'Sarabun',
      fontSize: 8,
    },
  }
}

/**
 * Downloads a PR document as a PDF
 * @param prData The Purchase Requisition data
 * @param filename Optional filename (defaults to PR_[prNo].pdf)
 */
export const downloadPRPdf = (prData: PurchaseRequisitionRespType, filename?: string) => {
  // Create the document definition
  const documentDefinition = createPRDocumentDefinition(prData)
  
  // Generate and download the PDF
  pdfMake.createPdf(documentDefinition).download(
    filename || `PR_${prData.prNo || 'document'}.pdf`
  )
}
