import { UploadFile } from 'antd'

export type mainGroupDropdownType = {
  id: string
  mainGroupCode: string
  mainGroupName: string
  mainGroupDetail?: string
  value: string
  label: string
}

export type PRAttachmentDataType = {
  key: string
  documentType: string
  documentNo: string
  documentDate: string
  fileName: string
  domain: string
  isUse?: boolean
  file?: UploadFile
  id?: string
  fileUrl?: string
  fileSize?: string
  mimeType?: string
  refId?: string
  prId?: string
}

export type PRDetailsFormValuesType = {
  projectName: string
  mainGroup: { value: string; label: string }
  requiredDate: string
  budgetType: { value: string; label: string }
  budgetCode: string
  line: string
  purpose: string
  currency: { value: string; label: string }
  exchangeRateSource: number
  exchangeRateDestination: number
  isBudgetCenterOnSite: boolean
}

// Reference: https://redux-toolkit.js.org/rtk-query/api/created-api/hooks#uselazyquery
export type UseQueryStateResult<T> = {
  // Base query state
  originalArgs?: unknown // Arguments passed to the query
  data?: T // The latest returned result regardless of trigger arg, if present
  currentData?: T // The latest returned result for the trigger arg, if present
  error?: unknown // Error result if present
  requestId?: string // A string generated by RTK Query
  endpointName?: string // The name of the given endpoint for the query
  startedTimeStamp?: number // Timestamp for when the query was initiated
  fulfilledTimeStamp?: number // Timestamp for when the query was completed

  isUninitialized: boolean // Query has not started yet.
  isLoading: boolean // Query is currently loading for the first time. No data yet.
  isFetching: boolean // Query is currently fetching, but might have data from an earlier request.
  isSuccess: boolean // Query has data from a successful load.
  isError: boolean // Query is currently in an "error" state.
}

export type PrItemType = {
  order?: number
  id?: string | null
  key: string
  budgetId: string
  budgetCode: string
  budgetSiteId: string
  budgetSiteName: string
  name?: string
  model?: string
  brand?: string
  detail?: string | null
  qty: number
  unit?: string
  unitPrice: number
  unitDiscount: number
  netTotal: number
  matCode: string | null
}

export type DropdownValueType = {
  label: string
  value: string
  id?: string
  title?: string
}

export type ExchangeRateType = {
  source: number | null
  destination: number | null
}

export type TPrDetailsData = {
  mainGroupId: number
  mainGroupName: string
  requiredDate: string
  budgetTypeId: number
  budgetTypeName: string
  budetCodeId: number
  budgetCode: string
  line: string
  purpose: string
  currencyId: number
  currencyName: string
  exchangeRateSource: number
  exchangeRateDestination: number
}

export type TPrQuotationFormValues = {
  quotationNo: string
  quotationDate: string
  supplier: string
}
