import { useCallback, useEffect, useState } from 'react'

import { PurchaseOrderRespType } from 'api/poApi.types.js'

import createBCSHeaderSection from 'components/pdf/BCSHeaderSection.js'
import createBCSTableSection from 'components/pdf/BCSTableSection.js'

import { formatDisplayDate } from 'utils/dateHelpers.js'

import pdfMake from 'pdfmake/build/pdfmake'
import { TDocumentDefinitions } from 'pdfmake/interfaces'

// @ts-expect-error vfs_fonts.js a custom file generated by pdfmake
import { vfs } from '../../../../pdfmake/vfs_fonts.js'

pdfMake.vfs = vfs

pdfMake.fonts = {
  Sarabun: {
    normal: 'Sarabun-Regular.ttf',
    bold: 'Sarabun-Bold.ttf',
    italics: 'Sarabun-Italic.ttf',
    bolditalics: 'Sarabun-BoldItalic.ttf',
  },
}

type BCSpdfBuilderProps = {
  poData: PurchaseOrderRespType
}

const BCSpdfBuilder = ({ poData }: BCSpdfBuilderProps) => {
  const [pdfUrl, setPdfUrl] = useState<string | null>(null)

  const generatePdf = useCallback(() => {
    const documentDefinition: TDocumentDefinitions = {
      footer: function (currentPage: number, pageCount: number) {
        return {
          text: 'Page ' + currentPage.toString() + '/' + pageCount,
          alignment: 'right',
          margin: [0, 0, 10, 0],
        }
      },
      header: undefined,
      content: [
        // NOTE: ------ BUDGET CONTROL SHEET PAGE ------
        {
          margin: [-20, -30, -20, 0],
          // pageBreak: 'before',
          layout: {
            // paddingTop: TABLE_LAYOUT.paddingTop,
            defaultBorder: false,
          },
          table: {
            widths: ['*'],
            body: [
              // NOTE: ------ HEADER ------
              createBCSHeaderSection({
                documentNo: poData.poNo,
                documentDate: formatDisplayDate(poData.poDate),
              }),
            ],
          },
        },
        {
          margin: [-20, 0, -20, 0],
          layout: {
            defaultBorder: true,
          },
          table: {
            widths: [
              20, // Fixed first column
              40, // Fixed second column
              70, // Fixed third column
              ...poData.purchaseOrderBudgetControlSheets.map(() => '*'), // Dynamic budget columns
            ],
            body: [
              ...createBCSTableSection({
                domain: 'PURCHASE_ORDER',
                budgets: poData.purchaseOrderBudgetControlSheets,
                budgetTypeName: poData.budgetTypeName,
                bcsRemark: poData.remarkBudgetControlSheet,
              }),
            ],
          },
        },
      ],
      defaultStyle: {
        font: 'Sarabun',
        fontSize: 8,
      },
    }

    // pdfMake.createPdf(documentDefinition).download('test.pdf') // NOTE: Download
    // pdfMake.createPdf(documentDefinition).open() // NOTE: Open in new tab
    pdfMake.createPdf(documentDefinition).getBlob((blob) => {
      const url = URL.createObjectURL(blob)
      setPdfUrl(url)
    })
  }, [poData])

  useEffect(() => {
    generatePdf()
  }, [generatePdf])

  return (
    <div>
      {pdfUrl && (
        <iframe src={pdfUrl} style={{ width: '100%', height: '80vh' }} title="PDF Preview" />
      )}
    </div>
  )
}

export default BCSpdfBuilder
