import { PurchaseOrderRespType } from 'api/poApi.types.js'

// import { createTableLayout } from 'utils/pdfHelpers'
import pdfMake from 'pdfmake/build/pdfmake'
import { CustomTableLayout, TDocumentDefinitions } from 'pdfmake/interfaces'

// @ts-expect-error vfs_fonts.js a custom file generated by pdfmake
import { vfs } from '../../../../pdfmake/vfs_fonts.js'

import createHeaderSection from './HeaderSection.js'
import createItemsTableSection from './ItemsTableSection.js'
import createPOInfoSection from './POInfoSection.js'
import createSignatureSection from './SignatureSection.js'

// Initialize pdfMake
pdfMake.vfs = vfs

pdfMake.fonts = {
  Sarabun: {
    normal: 'Sarabun-Regular.ttf',
    bold: 'Sarabun-Bold.ttf',
    italics: 'Sarabun-Italic.ttf',
    bolditalics: 'Sarabun-BoldItalic.ttf',
  },
}

/**
 * Helper function to calculate footer height based on import status
 */
export const getFooterHeight = (isImport: boolean) => (isImport ? 260 : 255)

/**
 * Creates a custom table layout for PO documents
 */
export const createPOTableLayout = (footerHeight: number): CustomTableLayout => ({
  paddingBottom: (rowIndex: number, node) => {
    const DEFAULT_PADDING = 2

    // Calculate padding for the last element of the table.
    if (rowIndex === node.table.body.length - 2) {
      // @ts-expect-error - positions property exists at runtime but not in type definition
      const currentPosition = node.positions[node.positions.length - 1]
      const totalPageHeight = currentPosition.pageInnerHeight
      const currentHeight = currentPosition.top

      let paddingBottom = totalPageHeight - currentHeight - footerHeight

      // NOTE: If footer cannot fit in the page, then return the space
      if (totalPageHeight - currentHeight < footerHeight) {
        paddingBottom = totalPageHeight - currentHeight - 25
      }

      // NOTE: If the padding bottom is less than 0, then return 0
      if (paddingBottom < 0) {
        return 0
      }

      return paddingBottom
    } else {
      return DEFAULT_PADDING
    }
  },
})

/**
 * Creates a PDF document definition for a Purchase Order
 * @param poData The Purchase Order data
 * @returns A pdfMake document definition
 */
export const createPODocumentDefinition = (poData: PurchaseOrderRespType): TDocumentDefinitions => {
  const footerHeight = getFooterHeight(poData.isImport)
  const tableLayout = createPOTableLayout(footerHeight)

  return {
    footer: function (currentPage: number, pageCount: number) {
      return {
        text: 'Page ' + currentPage.toString() + '/' + pageCount,
        alignment: 'right',
        margin: [0, 0, 10, 0],
      }
    },
    header: undefined,
    content: [
      // NOTE: ------ PO PAGE ------
      {
        margin: [-20, 0, -20, 0],
        layout: {
          paddingBottom: tableLayout.paddingBottom,
          defaultBorder: false,
        },
        table: {
          headerRows: 3,
          keepWithHeaderRows: 1,
          dontBreakRows: true,
          widths: [20, '*', 35, 40, 65, 60, 65],
          body: [
            // NOTE: ------ HEADER ------
            createHeaderSection(poData),
            // NOTE: ------ PO INFO SECTION ------
            createPOInfoSection(poData),
            // NOTE: ------ ITEMS TABLE SECTION ------
            ...createItemsTableSection(poData),
            // NOTE: ---- Signature Section ----
            createSignatureSection(poData),
          ],
        },
      },
    ],
    defaultStyle: {
      font: 'Sarabun',
      fontSize: 8,
    },
  }
}

/**
 * Downloads a PO document as a PDF
 * @param poData The Purchase Order data
 * @param filename Optional filename (defaults to PO_[poNo].pdf)
 */
export const downloadPOPdf = (poData: PurchaseOrderRespType, filename?: string) => {
  // Create the document definition
  const documentDefinition = createPODocumentDefinition(poData)
  
  // Generate and download the PDF
  pdfMake.createPdf(documentDefinition).download(
    filename || `PO_${poData.poNo || 'document'}.pdf`
  )
}
