// import { useCallback, useEffect, useState } from 'react'

// import dayjs from 'dayjs'

// import { mockQr } from 'assets/base64/mockQr.js'
// import { nhkLogo } from 'assets/base64/nhkLogo.js'
// import { clrBlack200, clrErrorRed, clrPrimary, clrWhite } from 'styles/theme'

// import { formatDisplayDate } from 'utils/dateHelpers.js'
// import { formatNumber } from 'utils/generalHelpers'

// import pdfMake from 'pdfmake/build/pdfmake'
// // import { CustomTableLayout, TDocumentDefinitions } from 'pdfmake/interfaces'
// import { TDocumentDefinitions } from 'pdfmake/interfaces'

// import { formatDescription } from '../features/purchaseRequisition/components/PdfPRRender/utils/pdfMeasurementUtils'
// import { mockItems } from '../mocks/items'
// // @ts-expect-error vfs_fonts.js a custom file generated by pdfmake
// import { vfs } from '../pdfmake/vfs_fonts.js'

// pdfMake.vfs = vfs

// pdfMake.fonts = {
//   Sarabun: {
//     normal: 'Sarabun-Regular.ttf',
//     bold: 'Sarabun-Bold.ttf',
//     italics: 'Sarabun-Italic.ttf',
//     bolditalics: 'Sarabun-BoldItalic.ttf',
//   },
// }

// // interface FooterContent {
// //   text: string
// //   alignment: 'left' | 'center' | 'right'
// //   margin: number[]
// // }

// const SIGNATURE_BOX_WIDTH = 88

// function ExamplePdfGenerator() {
//   const [pdfUrl, setPdfUrl] = useState<string | null>(null)
//   // const [selectedLayout, setSelectedLayout] = useState('lightHorizontalLines')
//   const budgetStatus = 'OVER BUDGET' // This would come from your actual data

//   // const TABLE_LAYOUT: CustomTableLayout = {
//   //   paddingTop: function (rowIndex, node) {
//   //     const DEFAULT_PADDING = 2

//   //     // Calculate padding for the last element of the table.
//   //     if (rowIndex === node.table.body.length - 1) {
//   //       // @ts-expect-error - positions property exists at runtime but not in type definition
//   //       const currentPosition = node.positions[node.positions.length - 1]
//   //       const totalPageHeight = currentPosition.pageInnerHeight
//   //       const currentHeight = currentPosition.top
//   //       const paddingTop = totalPageHeight - currentHeight
//   //       return paddingTop
//   //     } else {
//   //       return DEFAULT_PADDING
//   //     }
//   //   },
//   //   paddingBottom: function () {
//   //     return 2
//   //   },
//   // }

//   const getItemContent = () => {
//     return mockItems.map((item, index) => {
//       const isLastRow = index === mockItems.length - 1
//       return [
//         {
//           text: index + 1, // FIXME: need * if matCode.includes('DUMMY')
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//           alignment: 'center',
//         },
//         {
//           text: formatDescription(item),
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//         },
//         {
//           text: formatNumber(item.qty),
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//           alignment: 'right',
//         },
//         {
//           text: item.unit,
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//           alignment: 'center',
//         },
//         {
//           text: formatNumber(item.unitPrice),
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//           alignment: 'right',
//         },
//         {
//           text: formatNumber(item.unitDiscount),
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//           alignment: 'right',
//         },
//         {
//           text: formatNumber(item.netTotal),
//           border: [true, false, true, isLastRow],
//           borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//           borderWidth: [1, 0, 1, 1],
//           alignment: 'right',
//         },
//       ]
//     })
//   }
//   const generatePdf = useCallback(() => {
//     const items = getItemContent()
//     const documentDefinition: TDocumentDefinitions = {
//       footer: function (currentPage: number, pageCount: number) {
//         return {
//           text: 'Page ' + currentPage.toString() + '/' + pageCount,
//           alignment: 'right',
//           margin: [0, 0, 10, 0],
//         }
//       },
//       header: undefined,
//       content: [
//         {
//           margin: [-20, -30, -20, 0],
//           layout: {
//             // paddingTop: TABLE_LAYOUT.paddingTop,
//             defaultBorder: false,
//           },
//           table: {
//             headerRows: 4,
//             keepWithHeaderRows: 4,
//             dontBreakRows: true,
//             widths: [20, '*', 30, 40, 65, 60, 40],
//             body: [
//               // NOTE: ------ HEADER ------
//               [
//                 {
//                   colSpan: 7,
//                   columns: [
//                     {
//                       image: nhkLogo,
//                       width: 81,
//                       alignment: 'left',
//                       margin: [0, 20, 0, 0],
//                     },
//                     {
//                       width: '*',
//                       stack: [
//                         {
//                           text: 'บริษัท เอ็นเอชเค สปริง (ประเทศไทย) จำกัด',
//                           alignment: 'center',
//                           margin: [0, 10, 0, 0],
//                           fontSize: 10,
//                         },
//                         {
//                           text: 'NHK SPRING (THAILAND) CO.,LTD.',
//                           alignment: 'center',
//                           bold: true,
//                           fontSize: 10,
//                         },
//                         {
//                           text: [{ text: 'REQUIRE DATE : ', bold: true }, { text: '27/Jun/2025' }],
//                           margin: [0, 25, 0, 0],
//                           alignment: 'center',
//                         },
//                       ],
//                       alignment: 'center',
//                       margin: [0, 10, 0, 0],
//                     },
//                     {
//                       width: 'auto',
//                       stack: [
//                         { text: 'ต้นฉบับ / Original', alignment: 'right' },
//                         {
//                           image: mockQr,
//                           width: 60,
//                           alignment: 'right',
//                         },
//                         {
//                           text: [{ text: 'PR. DATE : ', bold: true }, { text: '03/Jun/2025' }],
//                           alignment: 'right',
//                           noWrap: true,
//                         },
//                       ],
//                       alignment: 'right',
//                     },
//                   ],
//                   columnGap: 10,
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//                 '', // Empty cells for colSpan
//               ],
//               // NOTE: ------ HEADER ------
//               [
//                 {
//                   colSpan: 7,
//                   text: 'PURCHASE REQUISITION #25-HO-01-PR',
//                   fillColor: clrPrimary,
//                   alignment: 'center',
//                   color: clrWhite,
//                   bold: true,
//                   margin: [0, -2, 0, -2],
//                   fontSize: 10,
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//               ],
//               // NOTE: ------ HEADER ------
//               [
//                 {
//                   colSpan: 7,
//                   columns: [
//                     {
//                       stack: [
//                         {
//                           columns: [
//                             { text: 'Name :', width: 50, bold: true },
//                             { text: 'MR. TANASIT PRASITKEDKIT', width: 'auto' },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Section :', width: 50, bold: true },
//                             { text: 'PURCHASING 2 (HO)', width: 'auto' },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Line :', width: 50, bold: true },
//                             { text: '-', width: 'auto' },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Site :', width: 50, bold: true },
//                             {
//                               text: 'consectetur adipiscing elit. Donec lobortis ultrices mi, nec molestie leo aliquet ultrices. Vestibulum orci mi, vehicula quis tempus ut, auctor nec ipsum. Pellentesque',
//                               width: 'auto',
//                             },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Main Group :', width: 50, bold: true },
//                             { text: '9.Information System', width: 'auto' },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Purpose :', width: 50, bold: true },
//                             {
//                               text: 'Lorem ipsum dolor sit amet',
//                               width: 'auto',
//                             },
//                           ],
//                           columnGap: 10,
//                         },
//                       ],
//                     },
//                     {
//                       stack: [
//                         {
//                           columns: [
//                             {
//                               columns: [
//                                 { text: 'Budget Type :', width: 60, bold: true },
//                                 { text: 'Investment Budget', width: '*' },
//                                 {
//                                   text: 'Budget Year :',
//                                   bold: true,
//                                   margin: [5, 0, 0, 0],
//                                   width: 'auto',
//                                 },
//                                 { text: '2025', alignment: 'right', width: 'auto' },
//                               ],
//                             },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Asset Type :', width: 60, bold: true },
//                             { text: 'PURCHASING 2 (HO)', width: 'auto' },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Main Budget No. :', width: 60, bold: true },
//                             { text: '-', width: 'auto' },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Sub Budget No. :', width: 60, bold: true },
//                             {
//                               text: 'consectetur adipiscing elit.',
//                               width: 'auto',
//                             },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Budget Desc. :', width: 60, bold: true },
//                             {
//                               text: ' Donec lobortis ultrices mi, nec molestie leo aliquet ultrices. Vestibulum orci mi, vehicula quis tempus ut, auctor nec ipsum. Pellentesque',
//                               width: 'auto',
//                             },
//                           ],
//                           columnGap: 10,
//                         },
//                         {
//                           columns: [
//                             { text: 'Jobs Name :', width: 60, bold: true },
//                             {
//                               text: 'Lorem ipsum dolor sit amet',
//                               width: 'auto',
//                             },
//                           ],
//                           columnGap: 10,
//                         },
//                       ],
//                     },
//                   ],
//                   columnGap: 10,
//                   margin: [0, 0, 0, 5],
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//                 '', // Empty cells for colSpan],
//               ],
//               [
//                 {
//                   text: 'NO.',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//                 {
//                   text: 'DESCRIPTION',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//                 {
//                   text: 'QTY',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//                 {
//                   text: 'UNIT',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//                 {
//                   text: 'UNIT PRICE',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//                 {
//                   text: 'UNIT DISCOUNT',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//                 {
//                   text: 'TOTAL',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   bold: true,
//                   alignment: 'center',
//                   border: [1, 1, 1, 0],
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                 },
//               ],
//               ...items,
//               // NOTE: ------ FOOTER: Grand Total ------
//               [
//                 {
//                   colSpan: 4,
//                   text: 'FIXME: NUMBER IN ALPHABET',
//                   bold: true,
//                   alignment: 'left',
//                   fillColor: clrBlack200,
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                   borderWidth: [1, 0, 1, 1],
//                   border: [1, 0, 1, 1],
//                 },
//                 '',
//                 '',
//                 '',
//                 {
//                   text: 'GRAND TOTAL',
//                   bold: true,
//                   alignment: 'center',
//                   borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                   borderWidth: [1, 0, 1, 1],
//                   border: [1, 0, 1, 1],
//                 },
//                 {
//                   colSpan: 2,
//                   text: 'FIXME: NUMBER IN BAHT',
//                   bold: true,
//                   alignment: 'right',
//                   fillColor: clrPrimary,
//                   color: clrWhite,
//                   // borderColor: [clrBlack200, clrBlack200, clrBlack200, clrBlack200],
//                   // borderWidth: [1, 0, 1, 1],
//                   // border: [1, 0, 1, 1],
//                 },
//                 '',
//               ],
//               // NOTE: ------ FOOTER: Summary Row ------
//               [
//                 {
//                   colSpan: 4,
//                   text: [{ text: 'REMARK : ', bold: true }, { text: 'FIXME - REMARK_CONTENT' }],
//                   alignment: 'left',
//                   border: [0, 0, 0, 0],
//                   margin: [0, 0, 0, 10],
//                 },
//                 '',
//                 '',
//                 '',
//                 {
//                   text: 'BUDGET STATUS :',
//                   bold: true,
//                   alignment: 'center',
//                   border: [0, 0, 0, 0],
//                   margin: [0, 0, 0, 10],
//                 },
//                 {
//                   colSpan: 2,
//                   text: budgetStatus,
//                   bold: true,
//                   alignment: 'center',
//                   color: budgetStatus === 'OVER BUDGET' ? clrErrorRed : undefined, // FIXME: need to fix this
//                   border: [0, 0, 0, 0],
//                   margin: [0, 0, 0, 10],
//                 },
//                 '',
//               ],
//               [
//                 {
//                   colSpan: 7,
//                   margin: [-4, 0, -4, 0],
//                   layout: {
//                     defaultBorder: false,
//                   },
//                   table: {
//                     widths: ['*', '*', '*', '*', '*', '*'],
//                     body: [
//                       [
//                         {
//                           colSpan: 6,
//                           text: 'REQUESTER DIVISION',
//                           bold: true,
//                           alignment: 'center',
//                           fillColor: clrPrimary,
//                           color: clrWhite,
//                           fontSize: 10,
//                           margin: [0, -2, 0, -2],
//                         },
//                         '',
//                         '',
//                         '',
//                         '',
//                         '',
//                       ],
//                       // NOTE: ------ REQUESTER DIVISION ------
//                       [
//                         { text: 'REQUESTER/CHIEF', alignment: 'center' },
//                         { text: 'MANAGER/DGM', alignment: 'center' },
//                         { text: 'GM.', alignment: 'center' },
//                         { text: 'FGM.', alignment: 'center' },
//                         { text: 'SDC./EMC./SD.', alignment: 'center' },
//                         { text: 'VP./SVP./EVP.', alignment: 'center' },
//                       ],
//                       // NOTE: ------ REQUESTER DIVISION: SIGNATURES ------
//                       [
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                       ],
//                       ['', '', '', '', '', ''],
//                       [
//                         {
//                           colSpan: 6,
//                           text: 'PURCHASE DIVISION',
//                           bold: true,
//                           alignment: 'center',
//                           fillColor: clrPrimary,
//                           color: clrWhite,
//                           fontSize: 10,
//                           margin: [0, -2, 0, -2],
//                         },
//                         '',
//                         '',
//                         '',
//                         '',
//                         '',
//                       ],
//                       // NOTE: ------ PURCHASE DIVISION ------
//                       [
//                         { text: 'RECEIVER', alignment: 'center' },
//                         { text: 'CHIEF.FACT.', alignment: 'center' },
//                         { text: 'MANAGER', alignment: 'center' },
//                         { text: 'RECEIVER HO. ', alignment: 'center' },
//                         { text: 'CHIEF HO.', alignment: 'center' },
//                         { text: 'MANAGER', alignment: 'center' },
//                       ],
//                       // NOTE: ------ REQUESTER DIVISION: SIGNATURES ------
//                       [
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                         {
//                           canvas: [
//                             {
//                               type: 'rect',
//                               x: -5,
//                               y: -3,
//                               w: SIGNATURE_BOX_WIDTH,
//                               h: 50,
//                               lineWidth: 1,
//                               lineColor: '#000',
//                             },
//                           ],
//                         },
//                       ],
//                     ],
//                   },
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//               ],
//               [
//                 {
//                   colSpan: 7,
//                   text: `REMARK: MANAGER < 5,000 ฿, DEPUTY GENERAL MANAGER < 10,000 ฿, GENERAL MANAGER/FACTORY GENERAL MANAGER/SENIOR DIRECTOR < 50,000 ฿,
//                   VICE PRESIDENT/SENIOR VICE PRESIDENT/EXECUTIVE VICE PRESIDENT > 50,000 ฿`,
//                   alignment: 'left',
//                   fontSize: 6,
//                   margin: [-5, -5, 0, 0],
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//               ],
//             ],
//           },
//         },
//         // NOTE: ------ BUDGET CONTROL SHEET PAGE ------
//         {
//           margin: [-20, -30, -20, 0],
//           pageBreak: 'before',
//           layout: {
//             // paddingTop: TABLE_LAYOUT.paddingTop,
//             defaultBorder: false,
//           },
//           table: {
//             widths: ['*'],
//             body: [
//               // NOTE: ------ HEADER ------
//               [
//                 {
//                   columns: [
//                     {
//                       image: nhkLogo,
//                       width: 81,
//                       alignment: 'left',
//                       margin: [0, 20, 0, 0],
//                     },
//                     {
//                       width: '*',
//                       stack: [
//                         {
//                           text: 'บริษัท เอ็นเอชเค สปริง (ประเทศไทย) จำกัด',
//                           alignment: 'center',
//                           margin: [0, 10, 0, 0],
//                           fontSize: 10,
//                         },
//                         {
//                           text: 'NHK SPRING (THAILAND) CO.,LTD.',
//                           alignment: 'center',
//                           bold: true,
//                           fontSize: 10,
//                         },
//                         {
//                           text: [{ text: 'REQUIRE DATE : ', bold: true }, { text: '27/Jun/2025' }],
//                           margin: [0, 25, 0, 0],
//                           alignment: 'center',
//                         },
//                       ],
//                       alignment: 'center',
//                       margin: [0, 10, 0, 0],
//                     },
//                     {
//                       width: 'auto',
//                       stack: [
//                         { text: 'ต้นฉบับ / Original', alignment: 'right' },
//                         {
//                           image: mockQr,
//                           width: 60,
//                           alignment: 'right',
//                         },
//                         {
//                           text: [{ text: 'PR. DATE : ', bold: true }, { text: '03/Jun/2025' }],
//                           alignment: 'right',
//                           noWrap: true,
//                         },
//                       ],
//                       alignment: 'right',
//                     },
//                   ],
//                   columnGap: 10,
//                 },
//               ],
//               // NOTE: ------ HEADER ------
//               [
//                 {
//                   text: 'BUDGET CONTROL SHEET/เอกสารควบคุมงบประมาณ',
//                   fillColor: clrPrimary,
//                   alignment: 'center',
//                   color: clrWhite,
//                   bold: true,
//                   margin: [0, -2, 0, -2],
//                   fontSize: 10,
//                 },
//               ],
//             ],
//           },
//         },
//         {
//           margin: [-20, 5, -20, 0],
//           layout: {
//             // paddingTop: TABLE_LAYOUT.paddingTop,
//             defaultBorder: true,
//           },
//           table: {
//             widths: [20, 40, 70, '*', '*', '*'],
//             body: [
//               [
//                 {
//                   colSpan: 6,
//                   text: 'BUDGET CONTROL SHEET',
//                   bold: true,
//                   alignment: 'center',
//                   fillColor: clrBlack200,
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//               ],
//               [
//                 {
//                   colSpan: 6,
//                   text: [
//                     { text: 'BUDGET TYPE', bold: true },
//                     { text: '   ' },
//                     { text: 'FIXME: BUDGET_TYPE_VALUE' },
//                   ],
//                 },
//                 '',
//                 '',
//                 '',
//                 '',
//                 '',
//               ],
//               [
//                 {
//                   colSpan: 3,
//                   text: 'BUDGET YEAR',
//                   bold: true,
//                 },
//                 '',
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_YEAR_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_YEAR_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_YEAR_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 {
//                   colSpan: 3,
//                   text: 'BUGDET STATUS',
//                   bold: true,
//                 },
//                 '',
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_STATUS_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_STATUS_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_STATUS_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 {
//                   colSpan: 3,
//                   text: 'COST CENTER',
//                   bold: true,
//                 },
//                 '',
//                 '',
//                 {
//                   text: 'FIXME: COST_CENTER_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: COST_CENTER_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: COST_CENTER_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               // NOTE: ------ MAIN ------
//               [
//                 {
//                   rowSpan: 2,
//                   text: 'MAIN',
//                   bold: true,
//                   alignment: 'center',
//                 },
//                 {
//                   colSpan: 2,
//                   text: 'BUDGET CODE',
//                   bold: true,
//                 },
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 '',
//                 {
//                   colSpan: 2,
//                   columns: [
//                     {
//                       width: '*',
//                       text: 'BUDGET AMOUNT',
//                       bold: true,
//                     },
//                     {
//                       width: 'auto',
//                       text: '(A)',
//                       alignment: 'right',
//                       bold: true,
//                     },
//                   ],
//                 },
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               // NOTE: ------ SUB ------
//               [
//                 {
//                   rowSpan: 2,
//                   text: 'SUB',
//                   bold: true,
//                   alignment: 'center',
//                 },
//                 {
//                   colSpan: 2,
//                   text: 'BUDGET CODE',
//                   bold: true,
//                 },
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 '',
//                 {
//                   colSpan: 2,
//                   columns: [
//                     {
//                       text: 'BUDGET AMOUNT',
//                       bold: true,
//                     },
//                   ],
//                 },
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_CODE_VALUE',
//                   alignment: 'right',
//                 },
//               ],
//               // NOTE: ------ PR. ------
//               [
//                 {
//                   rowSpan: 3,
//                   text: 'PR.',
//                   bold: true,
//                   alignment: 'center',
//                 },
//                 {
//                   // colSpan: 2,
//                   rowSpan: 2,
//                   text: 'WAITING FOR PO.',
//                   bold: true,
//                 },
//                 {
//                   columns: [
//                     {
//                       width: '*',
//                       text: 'PR. PENDING',
//                       bold: true,
//                     },
//                     {
//                       width: 'auto',
//                       text: '(B)',
//                       bold: true,
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 {
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: '(0)',
//                     },
//                     {
//                       width: '*',
//                       text: 'FIXME: PR_PENDING_VALUE',
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 {
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: '(0)',
//                     },
//                     {
//                       width: '*',
//                       text: 'FIXME: PR_PENDING_VALUE',
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 {
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: '(0)',
//                     },
//                     {
//                       width: '*',
//                       text: 'FIXME: PR_PENDING_VALUE',
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//               ],
//               [
//                 '',
//                 '',
//                 {
//                   columns: [
//                     {
//                       width: '*',
//                       text: 'PR. APPROVE',
//                       bold: true,
//                     },
//                     {
//                       width: 'auto',
//                       text: '(C)',
//                       bold: true,
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 {
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: '(0)',
//                     },
//                     {
//                       width: '*',
//                       text: 'FIXME: PR_PENDING_VALUE',
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 {
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: '(0)',
//                     },
//                     {
//                       width: '*',
//                       text: 'FIXME: PR_PENDING_VALUE',
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 {
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: '(0)',
//                     },
//                     {
//                       width: '*',
//                       text: 'FIXME: PR_PENDING_VALUE',
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//               ],
//               [
//                 '',
//                 {
//                   colSpan: 2,
//                   columns: [
//                     {
//                       width: '*',
//                       text: 'AMOUNT OF "THIS ORDER"',
//                       bold: true,
//                     },
//                     {
//                       width: 'auto',
//                       text: '(D)',
//                       bold: true,
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 '',
//                 {
//                   text: 'FIXME: AMOUNT_OF_THIS_ORDER',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: AMOUNT_OF_THIS_ORDER',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: AMOUNT_OF_THIS_ORDER',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 {
//                   colSpan: 3,
//                   columns: [
//                     {
//                       width: '*',
//                       text: 'LATEST ACCUMULATE PO. ISSUE',
//                       bold: true,
//                     },
//                     {
//                       width: 'auto',
//                       text: '(E)',
//                       bold: true,
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 '',
//                 '',
//                 {
//                   text: 'FIXME: LATEST_ACCUMULATE_PO',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: LATEST_ACCUMULATE_PO',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: LATEST_ACCUMULATE_PO',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 {
//                   colSpan: 3,
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: 'BUDGET REMAIN',
//                       bold: true,
//                     },
//                     {
//                       width: '*',
//                       text: 'F=A-(B+C+D+E)',
//                       bold: true,
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//                 '',
//                 '',
//                 {
//                   text: 'FIXME: BUDGET_REMAIN',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_REMAIN',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: BUDGET_REMAIN',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 {
//                   colSpan: 3,
//                   text: 'REMARK',
//                   bold: true,
//                 },
//                 '',
//                 '',
//                 {
//                   text: 'FIXME: REMARK',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: REMARK',
//                   alignment: 'right',
//                 },
//                 {
//                   text: 'FIXME: REMARK',
//                   alignment: 'right',
//                 },
//               ],
//               [
//                 {
//                   colSpan: 6,
//                   border: [0, 0, 0, 0],
//                   margin: [-5, 0, -5, 0],
//                   columns: [
//                     {
//                       width: 'auto',
//                       text: 'REMARK: PLEASE EXPLAIN DETAIL IN OVER BUDGET CASE (CANNOT EXCEED THE BUDGET 10% OF BUDGET AMOUNT (A), MAXIMUM 500,000 THB) ',
//                       fontSize: 6,
//                     },
//                     {
//                       width: '*',
//                       text: [
//                         { text: 'Print Date: ', bold: true },
//                         { text: formatDisplayDate(dayjs().toDate()) },
//                       ],
//                       fontSize: 6,
//                       alignment: 'right',
//                     },
//                   ],
//                 },
//               ],
//             ],
//           },
//         },
//       ],
//       defaultStyle: {
//         font: 'Sarabun',
//         fontSize: 8,
//       },
//     }

//     // pdfMake.createPdf(documentDefinition).download('test.pdf') // NOTE: Download
//     // pdfMake.createPdf(documentDefinition).open() // NOTE: Open in new tab
//     pdfMake.createPdf(documentDefinition).getBlob((blob) => {
//       const url = URL.createObjectURL(blob)
//       setPdfUrl(url)
//     })
//   }, [])

//   useEffect(() => {
//     generatePdf()
//   }, [generatePdf])

//   return (
//     <div>
//       {/* <div style={{ marginBottom: '20px' }}>
//         <label>Select Layout: </label>
//         <select
//           value={selectedLayout}
//           onChange={(e) => setSelectedLayout(e.target.value)}
//           style={{ marginLeft: '10px' }}
//         >
//           <option value="lightHorizontalLines">Light Horizontal Lines</option>
//           <option value="lightVerticalLines">Light Vertical Lines</option>
//           <option value="lightHorizontalLinesAndVerticalLines">
//             Light Horizontal & Vertical Lines
//           </option>
//           <option value="headerLineOnly">Header Line Only</option>
//           <option value="noBorders">No Borders</option>
//           <option value="streakHeader">Streak Header</option>
//         </select>
//       </div> */}
//       {/* <button onClick={generatePdf}>Generate PDF</button> */}
//       {pdfUrl && (
//         <iframe src={pdfUrl} style={{ width: '100%', height: '80vh' }} title="PDF Preview" />
//       )}
//     </div>
//   )
// }

// export default ExamplePdfGenerator
